"""Package real Blender renders and source evidence for model review B."""
from pathlib import Path
import hashlib,html,json,struct,re
ROOT=Path('D:/UE5.7/test1/ArtSource/Mechs/StyleUnification_20260919')
OUT=ROOT/'Production_v1'
MODELS=[
 ('SpiderMech','SpiderMech · 源网格低模','深蓝灰 / 赭黄 / 黑色骨架','SpiderMech_LowPoly_Concept_ThreeViews_v2.png','保留六条附肢、长尖足和分节翘尾；减面后整理装甲大面，保留外露液压结构。'),
 ('Mecha_01','Mecha 01 · 灰蓝','灰蓝 / 黑灰','Mecha_01_Concept_ThreeViews_v2.png','保留原机体比例和反关节腿，降低蓝色饱和度，补充舱盖边框与关节环。'),
 ('Mecha_02','Mecha 02 · 金黄','金黄 / 黑灰 / 银灰','Mecha_02_Concept_ThreeViews_v1.png','保留八边形前面板、圆鼓体积与四个后喷口，统一倒角和关节细节。'),
 ('Mech_Lightest','轻型机甲 · 封闭装甲','赭黄 / 深青绿','Mech_Lightest_Concept_ThreeViews_v4.png','根据原蓝图组件装配，移除驾驶员与舱内零件，新增封闭装甲和通风片，保留单枪与肩甲的不对称布置。'),
 ('FireWeapon_01','FireWeapon 01 · 三管','灰蓝 / 黑灰','Weapons_Concept_ThreeViews_v4.png','原网格实际为三根炮管；参考图少画一管，制作版以源模型为准保留三管，降低蓝色饱和度。'),
 ('MissileWeapon_01','MissileWeapon 01','灰红 / 银灰','Weapons_Concept_ThreeViews_v4.png','保留源模型的弹架、管口和侧接口，降低红色饱和度。'),
 ('Machinegun_lvl1','Machinegun · Lv1','赭黄 / 深青绿 / 琥珀灯','Weapons_Concept_ThreeViews_v4.png','保留原骨架和组件轮廓，整理色块并补充枪口边缘。'),
 ('Missile_01','独立导弹','银灰 / 深灰','Missile_Concept_ThreeViews_v2.png','沿用源弹体与尾翼，统一折面和金属表面，分离深灰连接环。'),
]
validation=json.loads((OUT/'model_validation.json').read_text(encoding='utf-8'))
render=json.loads((OUT/'review_b_render_status.json').read_text(encoding='utf-8'))
assert validation['success'] and render['success']
def record(p):
 d=p.read_bytes();r={'path':p.relative_to(ROOT).as_posix(),'bytes':len(d),'sha256':hashlib.sha256(d).hexdigest()}
 if p.suffix=='.png':r['width'],r['height']=struct.unpack('>II',d[16:24])
 return r
blend=OUT/'Mechs_Style_SourceBased_v1.blend'
assert record(blend)['sha256']==render['blend_sha256'],'Preview is stale relative to blend'
views=[('Hero','效果'),('Front','正视'),('Side','侧视'),('Rear','背视')]
sections=[];cards=[];records=[];table=[]
for key,title,palette,concept,note in MODELS:
 tris=validation['models'][key]['triangles']
 figs=''.join(f'<figure><a href="Previews/{key}_{v}.png"><img loading="lazy" src="Previews/{key}_{v}.png" alt="{title} {label}"></a><figcaption>{label} / {v.upper()}</figcaption></figure>' for v,label in views)
 sections.append(f'<section id="{key}"><header><div><small>{key}</small><h2>{title}</h2></div><span class="badge">{tris:,} tris</span></header><p class="palette">{palette}</p><p>{note}</p><div class="views">{figs}</div><details><summary>展开已放行的造型与配色参考</summary><a href="../Concepts/{concept}"><img class="concept" loading="lazy" src="../Concepts/{concept}" alt="{title} 参考图"></a></details></section>')
 cards.append(f'<a class="card" href="#{key}"><img src="Previews/{key}_Hero.png" alt="{title}"><span>{title}</span></a>')
 records.append({'asset':key,'title':title,'triangles':tris,'concept':record(ROOT/'Concepts'/concept),'renders':[record(OUT/'Previews'/f'{key}_{v}.png') for v,_ in views]})
 table.append(f'<tr><td>{key}</td><td>{tris:,}</td></tr>')
sp=validation['spider'];gray=''.join(f'<div class="compare-view" data-view="{v}"'+('' if v=='Hero' else ' hidden')+f'><figure><a href="Previews/SpiderMech_SourceGray_{v}.png"><img src="Previews/SpiderMech_SourceGray_{v}.png" alt="原始灰模"></a><figcaption>原模型 · 839,778 tris</figcaption></figure><figure><a href="Previews/SpiderMech_FinalGray_{v}.png"><img src="Previews/SpiderMech_FinalGray_{v}.png" alt="减面后的灰模"></a><figcaption>制作版 · {sp["output_triangles"]:,} tris</figcaption></figure></div>' for v,_ in views)
buttons=''.join(f'<button type="button" data-pick="{v}" class="'+('selected' if v=='Hero' else '')+f'">{label}</button>' for v,label in views)
page='''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GuLiStrike / 源模型制作 / Review B</title><style>
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#ebece8;color:#273235;font:15px/1.7 "Segoe UI","Microsoft YaHei",sans-serif}main{max-width:1560px;margin:auto;padding:40px 28px 80px}.eyebrow{letter-spacing:3px;color:#6d7e83;font-size:12px}h1{font-size:clamp(30px,4vw,52px);line-height:1.2;margin:14px 0}h2{font-size:26px;margin:0}p{max-width:1080px;color:#526267}a{color:#365f75}nav{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}nav a,.badge,button{border:1px solid #bdc6c4;padding:6px 14px;border-radius:25px;text-decoration:none;background:#f9faf6;color:#365360}button{cursor:pointer;font:inherit}.selected{background:#365360;color:#fff}.summary{border-left:4px solid #9c823e;padding:12px 22px;background:#f7f6f0;margin:24px 0}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0 44px}.card{text-decoration:none;background:#f9faf7;border:1px solid #d1d8d3;border-radius:8px;overflow:hidden}.card img{width:100%;display:block}.card span{display:block;padding:12px;font-weight:600}section{background:#f7f8f4;border:1px solid #cfd6d1;padding:24px;margin:30px 0;border-radius:10px;scroll-margin:18px}header{display:flex;justify-content:space-between;align-items:center;gap:16px}small{font-size:12px;letter-spacing:1px;color:#7b898d}.badge{white-space:nowrap;font-variant-numeric:tabular-nums}.palette{color:#8e6e36;margin:8px 0}.views{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:24px 0}figure{margin:0;min-width:0}figure img{display:block;width:100%}figcaption{color:#708084;font-size:12px;padding:7px 4px;text-align:center;letter-spacing:1px}.concept{width:100%;margin-top:18px}summary{cursor:pointer;color:#365f75}details{margin-top:18px}.compare-view{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.compare-view[hidden]{display:none}.controls{display:flex;gap:8px;margin-top:18px}.tech{display:grid;grid-template-columns:1fr 1fr;gap:40px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{padding:8px;border-bottom:1px solid #d5dcd6;text-align:left}td:last-child{text-align:right}footer{color:#66797c;font-size:13px;margin-top:40px}@media(max-width:950px){.cards,.views{grid-template-columns:repeat(2,1fr)}.tech{grid-template-columns:1fr}}@media(max-width:600px){main{padding:24px 12px}.cards{gap:8px}.card span{font-size:12px}section{padding:14px}h2{font-size:20px}.compare-view{grid-template-columns:1fr}.badge{font-size:11px}}
</style></head><body><main><div class="eyebrow">GULISTRIKE / SOURCE-BASED MODEL PRODUCTION / 2026.09.19</div><h1>机甲风格统一 · 实际模型</h1><p>四种机体、三套武器与独立导弹。以下效果图和三视图均由交付的 Blender 网格直接渲染。</p>'''+f'<div class="summary">SpiderMech：<strong>839,778 → {sp["output_triangles"]:,} 三角面</strong>，减少 {sp["reduction_percent"]:.2f}%。<br>保留各自配色，红蓝降低饱和度；轻型机甲驾驶区封闭，不显示驾驶员与开放驾驶舱。<br><small>当前为 Blender 成品 B 候选，待用户审阅；UE 正式资源尚未替换。</small></div>'+'''<nav><a href="Mechs_Style_SourceBased_v1.blend">Blender 源文件</a><a href="#comparison">SpiderMech 原模对照</a><a href="#delivery">交付说明</a><a href="../Review_A_v2.html">参考图总览</a></nav><div class="cards">'''+''.join(cards)+'</div>'+''.join(sections)+f'<section id="comparison"><header><h2>SpiderMech · 同角度灰模对照</h2></header><p>原模型与制作版使用相同正交相机、尺度、光照和灰材质，便于检查轮廓、关节与装甲简化。</p><div class="controls">{buttons}</div>{gray}</section>'+'''<section id="delivery"><h2>交付与检查</h2><div class="tech"><div><p>可编辑模型保留原始导入副本，制作网格位于 WORK 集合。Blender 内提供八个 Review 场景，便于逐件检查。SpiderMech 的减面修改器源文件和装甲整理候选另存于 Construction。</p><p>原骨骼名称与父子关系、UV 层和源材料槽已核对；新增细节绑定原活动骨骼，轻型机甲按原挂点关系装配。姿态检查为基本变形检查，完整动画及 UE 中的着色、碰撞与性能尚未验证。</p><p>本批保留原受光类别，在 Blender 用 Principled 预览对应表面。干净色块与表面参数已调整；原 UE 材质网络保持原样。</p><p><a href="README.md">制作说明</a> · <a href="model_validation.json">模型检查</a> · <a href="production_manifest.json">文件及 SHA256 清单</a></p></div><table><thead><tr><th>实际渲染网格</th><th>三角面</th></tr></thead><tbody>'''+''.join(table)+'''</tbody></table></div></section><footer>参考 A 已由“开始制作”指令放行；实际成品 B 不预填通过。当前结果基于实际源网格制作，二维生成参考仅用于造型与配色对照。</footer></main><script>document.querySelectorAll('[data-pick]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-pick]').forEach(x=>x.classList.toggle('selected',x===b));document.querySelectorAll('[data-view]').forEach(x=>x.hidden=x.dataset.view!==b.dataset.pick)})</script></body></html>'''
(OUT/'Review_B_v1.html').write_text(page,encoding='utf-8')
evidence=['model_validation.json','root_weight_restore.json','light_closed_cockpit_report.json','review_b_render_status.json','production_authorization.json','import_report.json','spider_armor_cleanup.json','review_scenes.json']
manifest={'work_id':'WORK-20260919-004','version':1,'source_based':True,'reference_A':'released_for_production_by_user','review_B':'pending','ue_import':'not_started','blend':record(blend),'review':record(OUT/'Review_B_v1.html'),'models':records,'spider':sp,'evidence':[record(OUT/f) for f in evidence if (OUT/f).exists()],'source_snapshot':record(ROOT/'Source/Production_v1/source_snapshot.json'),'source_contracts':record(ROOT/'Source/Production_v1/socket_contracts.json'),'gray_comparisons':[record(OUT/'Previews'/f'SpiderMech_{label}_{v}.png') for label in ['SourceGray','FinalGray'] for v,_ in views],'known_reference_correction':'FireWeapon_01 source has three barrels; concept has two. Source geometry is authoritative.'}
manifest['construction']=[record(OUT/'Construction'/f) for f in ['SpiderMech_ReductionEditable.blend','SpiderMech_ArmorCleanCandidate.blend']]
scripts=Path('D:/UE5.7/test1/Scripts')
manifest['production_scripts']=[{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [scripts/'export_mech_production_sources.py',scripts/'inspect_mech_socket_contracts.py',scripts/'build_mech_production_review.py',*[scripts/'Blender'/n for n in ['import_mech_production_sources.py','mech_production_common.py','reduce_spider_source_mesh.py','style_mech_source_models.py','close_and_assemble_light_mech.py','refine_mech_surfaces_and_details.py','refine_spider_armor_candidate.py','finalize_mech_detail_fit.py','fit_mecha01_cap_contacts.py','validate_mech_production.py','prepare_mech_review_scenes.py','render_mech_review_b.py']]]]
(OUT/'production_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2),encoding='utf-8')
missing=[]
for link in re.findall(r'(?:href|src)="([^"]+)"',page):
 if not link.startswith('#') and not (OUT/link.split('#')[0]).exists():missing.append(link)
assert not missing,missing
(OUT/'delivery_validation.json').write_text(json.dumps({'success':True,'render_count':len(render['renders']),'missing_local_links':missing,'blend_matches_render_source':True,'models':len(MODELS)},indent=2),encoding='utf-8')
print(json.dumps({'review':str(OUT/'Review_B_v1.html'),'models':len(MODELS),'renders':len(render['renders']),'spider_triangles':sp['output_triangles']},ensure_ascii=False))
