"""Reconcile completed B evidence and the actual A release into existing project records."""
import json,re,hashlib
from pathlib import Path
W=Path('D:/UE5.7/test1');R=W/'ArtSource/Buildings/SSFStyle_20261005';O=R/'Production_B_v1';P=W/'Progress'
validation=json.loads((R/'DeliveryValidation_B_v1.json').read_text(encoding='utf8'));assert validation['all_current_files_exist_and_match_hash']
manifest=json.loads((O/'production_manifest.json').read_text(encoding='utf8'));model=manifest['source_blend_sha256'];mh=validation['manifest_sha256'];A=json.loads((R/'approval_A.json').read_text(encoding='utf8'))
def metadata(text,**fields):
 for name,value in fields.items():text,count=re.subn(r'^'+re.escape(name)+r':.*$',name+': '+value,text,count=1,flags=re.M);assert count==1,name
 return text
req=P/'RequirementDocument/20261005-SSF建筑美术统一与三档LOD.md';text=req.read_text(encoding='utf8')
text=metadata(text,summary='A_v7已获制作放行；实际Blender B_v1含十类资产、三档LOD与22完整动画，B及24项本体预算例外待审核，正式UE导入未执行。',next_action='审核具体SSF_Production_B_v1的外观和运动，并明确决定24项本体预算差额例外或继续调整；B放行后导出回读并正式导入。',status_note='用户开始制作指令对应A_v7放行；B_v1实际成品已提交。技术检查通过不等于B或预算例外通过，未覆盖商城源包。')
text=text.replace('当前A_v7保持本表配色，并修正线稿与明暗表现；用户选定A_v3作为修改基准及本轮反馈都不等于A_v7或完整A/B审核通过。','A_v7保持本表配色，并修正线稿与明暗表现。随后用户明确“开始制作，严格一比一按照参考图和原模型制作”，作为具体A_v7制作放行，见[决定记录](../../ArtSource/Buildings/SSFStyle_20261005/approval_A.json)。这不代表尚未展示成品的B通过。')
text=text.replace('- [ ] 用户审核具体参考版本A。','- [x] 用户对已展示A_v7发出明确制作指令，登记A_v7放行及固定清单哈希。')
text=text.replace('- [ ] 按已审图完成可编辑Blender成品、三档LOD和22动画兼容检查。','- [x] 按已审图与源模型完成可编辑Blender B_v1、三档LOD及22动画原生检查/完整预览；正式UE兼容回读留在B后。\n- [ ] 决定24项本体预算例外；预算上限并未自动调整，描边已达上限。')
text+='\n## 2026-10-05 实际成品 B_v1 提交\n\n[实际成品审核](../../ArtSource/Buildings/SSFStyle_20261005/Review_B_v1.md)交付十类资产、792制作分件、355骨骼、三档LOD、42张2K效果/正交图、参考同机位/LOD对比及22个完整视频。绑定保留源Root/层级/动作名称，金属刚性，克隆软管柔性；内部线稿为独立RG遮罩，近中档是真实绑定描边壳，远档细线与壳为0。\n\n原结构保护优先于超出容差的减面，六座建筑、平台和无人机共24档本体高于原定上限，见[实际差额与对比](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/Budget_Exceptions.md)。真实壳仅覆盖预算内主要构件，部分轮廓比参考Freestyle细；此视觉差异明确提交B，不记为用户已接受。原预算保持，B与例外待决定。\n\n视频从6003个30fps源姿态重现，15fps成品完整预览共3012帧，全部22个MP4回读与110个检查帧对照完成。Blender实际变形检查通过；FBX导出回读、正式UE材质/LOD/动画/物理资产/无人机蓝图与项目镜头均未执行。\n'
req.write_text(text,encoding='utf8')
dev=P/'DevelopmentDocumentation/20261005-SSF建筑美术统一与三档LOD.md';text=dev.read_text(encoding='utf8')
text=metadata(text,summary='已审A_v7与原模型制作实际Blender B_v1，十类资产三档LOD和22完整动作预览/回读完成；24档本体超额及B待用户决定。',next_action='审核SSF_Production_B_v1实际外观/运动、轮廓表现与24项本体预算例外；通过后执行导出回读和UE正式副本交付。',status_note='A_v7依据用户开始制作指令放行；B_v1已提交。原生网格/骨架/实际变形和视频回读通过，用户B、预算例外、正式UE和实战验证尚未通过。')
text=text.replace('## 当前入口与阶段\n','## 当前入口与阶段\n\n当前为实际成品 **B_v1待审核**，原A_v7依据用户“开始制作，严格一比一按照参考图和原模型制作”放行，清单SHA256固定。\n\n- [实际Blender成品审核B_v1](../../ArtSource/Buildings/SSFStyle_20261005/Review_B_v1.md)\n- [完整图板与22个视频](../../ArtSource/Buildings/SSFStyle_20261005/review_B_v1.html)\n- [本体预算例外](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/Budget_Exceptions.md)\n- [B_v1冻结交付](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/production_manifest.json)\n- [A_v7放行](../../ArtSource/Buildings/SSFStyle_20261005/approval_A.json)\n\n下列A_v7/A_v6条目保留参考制作事实，其当时“待审/未制作”状态由以上最新决定和B_v1制作记录接续。\n')
text=text.replace('当前为参考A，设计图以实际源网格的同一中立姿态、同一正交尺度生成。','参考阶段为A，设计图以实际源网格的同一中立姿态、同一正交尺度生成。')
text=text.replace('- [ ] 用户A：待审核SSF_Reference_A_v7；风格问题反馈和修正不记为新版本的A通过。','- [x] 用户A：以已展示SSF_Reference_A_v7为依据发出开始制作指令，记录版本/哈希/原话。')
text=text.replace('- [ ] 实际Blender成品B：未开始。','- [x] 实际Blender B_v1制作、三档LOD、22动作及全部实际视频完成。\n- [ ] 用户审核B_v1实际成品、描边表现和24项本体预算例外。')
section=f'''\n## 实际 Blender B_v1 制作与交付\n\n用户最新原话“{A['user_quote']}”对应A_v7放行，[A记录](../../ArtSource/Buildings/SSFStyle_20261005/approval_A.json)固定清单哈希 `{A['manifest_sha256']}`。本体、配色和装配从已审实际参考/源模型提取，所有参考A_v1–A_v7冻结文件本轮重新核对保持。\n\n本版恢复7套真实Root/355骨骼及名称/层级/参考轴心；792分件保持在各档，镜像不交换刚性零件骨骼权重，克隆中心软管保留源柔性。清理重合点、退化/共面冗余及安全分段，减面以中间维度保护细长截面；禁止丢分件、破坏闭合拓扑或超过逐件表面/边界容差。源商城包未修改。\n\n内部线稿RG独立图集、固定艺术光与三档因子按A_v7，Base Color/Team Color接口保留；真实绑定描边壳在预算内选主要不透明构件，远档无壳并淡出内部线。Light保留2面原单面贴片和1K源遮罩，不伪造实体边框。半透明显示保留，实际近中档最多3材质区段。\n\n十类资产都有42张2048px原始效果/正交图、十套图板、十套A_v7同机位对照和十套三档LOD图；两张4096px原尺寸组合及真实材质拆分同时交付。参考Freestyle与真实壳的覆盖/线宽有差异，部分轮廓比参考细，已在B明确列出；用户严格视觉一致性仍待决定。\n\n22个原名Action来自UE只读采集6003个30fps姿态。7套源骨架动作T/R/S均保留，完整15fps视频共3012帧，单视频三个实际LOD并排同播；原Destoy/Edle名称不改。22动作每个5检查点、各3LOD全部本体顶点与源骨骼变换最大差5.888243316e-6m，源实际骨骼抽样矩阵最大差4.768371582e-6。全部22个MP4实际解码、帧数/1920×768/15fps及110检查帧对照完成；助手动画读图与用户B单列。\n\n[24项本体预算差额](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/budget_exception_record.json)覆盖六座建筑/平台/无人机三档；本体未达原上限，差额未批准。描边全部在上限内，灯柱48面、灯片2面保持。建筑2K、平台4K、无人机/灯具1K共38张唯一新PNG；字节/未压缩RGBA8等价预算留档，未测UE压缩/驻留和实战帧率。\n\nBlender SHA256 `{model}`；冻结清单SHA256 `{mh}`，[交付核对](../../ArtSource/Buildings/SSFStyle_20261005/DeliveryValidation_B_v1.json)确认{validation['tracked_files']}个交付文件哈希一致。具体[审核B_v1](../../ArtSource/Buildings/SSFStyle_20261005/Review_B_v1.md)、[原生检查](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/native_validation.json)、[实际变形](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/animation_deformation_validation.json)、[视频回读](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/AnimationPreviews/movie_readback_report.json)、[助手视觉检查](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/visual_qa.json)分别保存。\n\nB与预算例外待用户决定。正式FBX导出回读、UE正式副本/物理资产/22动画/无人机蓝图、保存重载引用、三档指挥官镜头及实战帧率尚未执行，不宣称引擎兼容或性能已终验。本轮不用功能开发Map/PIE/构建流程。\n'''
text+=section;dev.write_text(text,encoding='utf8')
rule=P/'RequirementDocument/GuLiStrike美术规范.md';text=rule.read_text(encoding='utf8');old='A_v1至A_v6保留历史，A_v7待审核、B未开始；';new='A_v1至A_v6保留历史，A_v7依据用户“开始制作，严格一比一按照参考图和原模型制作”已放行，见[A决定](../../ArtSource/Buildings/SSFStyle_20261005/approval_A.json)。当前[实际Blender成品B_v1](../../ArtSource/Buildings/SSFStyle_20261005/Review_B_v1.md)保留原结构/骨架/22动作并交付三档LOD；B与24项本体预算例外待审核，部分真实壳轮廓比参考细，正式UE尚未导入；';assert old in text;text=text.replace(old,new,1);rule.write_text(text,encoding='utf8')
ledger=P/'DevelopmentDocumentation/GuLiStrike美术规范.md';text=ledger.read_text(encoding='utf8');text+=f'''\n## 2026-10-05 SSF A_v7制作放行与实际成品 B_v1\n\n用户明确“{A['user_quote']}”，作为已展示SSF_Reference_A_v7的制作放行，[A决定](../../ArtSource/Buildings/SSFStyle_20261005/approval_A.json)固定清单 `{A['manifest_sha256']}`，不记为尚未展示B的通过。七个参考版本原样保留。\n\n当前[实际Blender B_v1](../../ArtSource/Buildings/SSFStyle_20261005/Review_B_v1.md)交付十类资产、792分件、355骨骼、三档LOD、独立线稿与真实描边壳，保持A_v7全部配色及三档因子。42张2K效果/正交图、参考同机位/三档LOD对比、两张4K组合、全部22原名完整动画预览与MP4回读完成；6003源姿态留存，实际变形抽样最大位置差5.888243316e-6m。\n\n原结构保护下[24档本体差额](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/Budget_Exceptions.md)未达原上限，例外未批准；描边预算达标但部分覆盖/线宽弱于参考Freestyle，提交用户B决定。实际成品SHA256 `{model}`，冻结清单 `{mh}`；[当前核对](../../ArtSource/Buildings/SSFStyle_20261005/DeliveryValidation_B_v1.json)记录{validation['tracked_files']}个交付文件哈希保持。\n\nB与预算例外待审核，正式UE导入、导出回读、引用/物理资产/无人机蓝图和项目指挥官镜头均未执行；资源预算和Blender检查不替代实战帧率。全局规范仍v1.3，增量见[归档](../Archive/20261005-SSF建筑Blender成品B_v1与预算例外.md)。\n''';ledger.write_text(text,encoding='utf8')
archive=P/'Archive/20261005-SSF建筑Blender成品B_v1与预算例外.md';assert not archive.exists()
for path in (P/'Archive').glob('20261005*.md'):assert not re.search(r'^id: ARC-20261005-011\s*$',path.read_text(encoding='utf8'),re.M),'Archive id became occupied'
archive.write_text(f'''---\nschema: guli-progress/v1\nid: ARC-20261005-011\nwork_id: ''\nkind: archive\nrole: root\ntitle: SSF建筑Blender成品B_v1与预算例外\nareas: [art, assets, rendering]\ncategories: [art]\nstatus: recorded\nverification: partial\ncreated: '2026-10-05'\nupdated: '2026-10-05'\nsummary: A_v7依用户制作指令放行；实际B_v1十类资产、三档LOD、22完整动作与回读交付，24档本体超额及用户B待审，正式UE未导入。\nnext_action: 用户审核具体SSF_Production_B_v1外观/运动及24项本体差额，决定预算例外或调整后再审；B后导出回读并正式UE交付。\nrelations:\n  work_items: [WORK-20261005-003]\nstatus_note: 原生几何/骨架/动作与视频检查通过，技术通过不替代用户B或预算例外；部分描边弱于参考，导出/引擎与帧率未验收。\nart_revision: '1.3'\n---\n\n# 2026-10-05：SSF A_v7放行后实际 Blender B_v1\n\n## 依据与范围\n\n用户明确“{A['user_quote']}”，作为已展示A_v7的制作授权，[A决定](../../ArtSource/Buildings/SSFStyle_20261005/approval_A.json)固定清单 `{A['manifest_sha256']}`。未把该指令当作尚未展示成品的B或正式UE通过。处理六座建筑与Floor/Lamp/Light/Drone，保留22原动画名及源商店包。\n\n## 实际制作与资源清单\n\n| 最终项目内目录 | 来源 | 内容与用途 | 依赖与边界 |\n|---|---|---|---|\n| `ArtSource/Buildings/SSFStyle_20261005/Production_B_v1` | `/Game/Assets/SSF_Buildings/Buildings` 的API导出源与已审A_v7 | Blender实际分件/镜像/修改器、十类资产三档LOD、7骨架355骨骼、22原名Action、38新贴图、原始渲染/图板/视频与回读 | 原骨骼/轴心、柔性克隆软管及半透明显示保留；源贴图与样本在同任务Source/AnimationSource；不迁入示例关卡/外部Actor目录，不修改UE源包。 |\n| `ArtSource/Buildings/SSFStyle_20261005` | 本任务现有参考/输入/Source | A授权记录、B具体审核页、版本决定与冻结清单 | A_v1–A_v7冻结不改；工作中间blend/日志不列为正式成品交付。 |\n| `/Game/GuLiStrike/Buildings/SSFStylized` | B审核通过后拟交付 | 本轮尚未创建正式资产；规划网格/骨架/动画/物理资产/材质/蓝图副本 | FBX导出回读、UE引用/材质/三档镜头留在B后；本行只定位后续正式资源目标。 |\n\n清理兼容权重的重合点、冗余共面/退化面及安全分段，保持每档全部792制作分件。真实Root与原名称/层级恢复，镜像不交换左右武器权重，金属刚性，克隆软管按源柔性。固定艺术光、A_v7色块/三档因子、内部RG遮罩、真实绑定描边壳与远档线稿淡出已制作。\n\n六座建筑、平台和无人机各三档，共24档本体超出原上限，[实际差额](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/Budget_Exceptions.md)与十套同机位LOD对比提交例外；原预算未更改。描边全部达预算，但仅在主要构件覆盖，部分轮廓弱于参考Freestyle，明确提交B。灯柱48面/灯片2面不强行减少，近中最多3区段。\n\n## 证据与验证\n\n[完整B审核](../../ArtSource/Buildings/SSFStyle_20261005/Review_B_v1.md)包括42张2K效果/正交图、十套实际三视图图板、十套参考同机位/LOD对比、两张4K原尺寸组合、实际材质拆分。22完整MP4三个真实LOD同播，15fps共3012帧，准确起止；30fps源6003姿态留档。全部22MP4实际解码检查帧数/1920×768/15fps，110回读检查帧与原渲染对照。\n\n[网格/权重/材质核对](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/native_validation.json)与[实际22动作×3LOD变形](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/animation_deformation_validation.json)通过，后者每动作5点对全部顶点最大位置差5.888243316e-6m，实际骨骼矩阵最大差4.768371582e-6。助手[视觉读图](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/visual_qa.json)单列，不等于用户B。\n\n成品Blender SHA256 `{model}`；[冻结清单](../../ArtSource/Buildings/SSFStyle_20261005/Production_B_v1/production_manifest.json)SHA256 `{mh}`；[交付核对](../../ArtSource/Buildings/SSFStyle_20261005/DeliveryValidation_B_v1.json)验证{validation['tracked_files']}个文件及七个历史参考版本。38贴图文件大小与RGBA8等价预算记录，不宣称引擎压缩/实际驻留或帧率达标。\n\n## 尚未完成与用户决定\n\nB_v1及24项本体预算例外均待用户明确决定。Blender与源运动检查只证明本阶段制作，FBX导出回读和UE正式副本/物理资产/22动画/无人机蓝图、引用重载、自动LOD与项目镜头尚未执行，实战帧率未测。未运行PIE/原生构建或覆盖商城源包。按用户流程与模型技能提交实际可审产物后止于B，全局美术规范仍v1.3。\n''',encoding='utf8')
decisions=json.loads((R/'review_decisions.json').read_text(encoding='utf8'));decisions['current_version']='SSF_Production_B_v1';decisions['B']={'status':'pending_user_decision','version':'SSF_Production_B_v1','source_blend_sha256':model,'manifest_sha256':mh,'user_approval':None};decisions['budget_exception_decision']={'status':'pending_user_decision','count':24,'record':'Production_B_v1/budget_exception_record.json'};decisions['history'].append({'version':'SSF_Production_B_v1','B':'pending_user_decision','manifest_sha256':mh,'body_budget_exceptions':'24_pending','reference_version':'SSF_Reference_A_v7','UE_formal_import_performed':False});(R/'review_decisions.json').write_text(json.dumps(decisions,ensure_ascii=False,indent=2),encoding='utf8')
readme=R/'README.md';old=readme.read_text(encoding='utf8');old=old.replace('# SSF 建筑制作源目录','# SSF 建筑制作源目录\n\n当前为实际 Blender **SSF_Production_B_v1，待审核B与24项本体预算例外**。用户已明确开始制作，A_v7放行。\n\n- [实际成品、三视图、对照与动画](Review_B_v1.md)\n- [完整图板与22个完整视频](review_B_v1.html)\n- [可编辑成品Blender](Production_B_v1/SSF_Production_B_v1.blend)\n- [本体预算差额](Production_B_v1/Budget_Exceptions.md)\n- [冻结B清单](Production_B_v1/production_manifest.json)\n- [本次A决定](approval_A.json)\n- [B交付哈希核对](DeliveryValidation_B_v1.json)\n\n原模型装配/主要比例及A_v7全部色值保持，真实线稿/三档/三LOD与22动作已制作。B和预算例外尚未通过，正式UE未导入；部分真实壳轮廓比参考细，B对照页明确列出。以下保留原参考阶段入口和当时说明，最新状态以上段与决定登记为准。',1);readme.write_text(old,encoding='utf8')
print('SSF_PROGRESS_AND_DECISIONS_UPDATED',mh,flush=True)
